{
 "title": "Apps: Latency",
 "tags": [ "apps" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values(cf_application_info, environment)"
   },
   {
    "name": "bosh_deployment",
    "label": "Deployment",
    "query": "label_values(cf_application_info{environment=~\"$environment\"}, deployment)"
   },
   {
    "name": "cf_organization_name",
    "label": "Organization",
    "query": "label_values(cf_application_info{environment=~\"$environment\",deployment=~\"$bosh_deployment\"}, organization_name)"
   },
   {
    "name": "cf_space_name",
    "label": "Space",
    "query": "label_values(cf_application_info{environment=~\"$environment\",deployment=~\"$bosh_deployment\",organization_name=~\"$cf_organization_name\"}, space_name)"
   },
   {
    "name": "cf_application_name",
    "label": "Application",
    "query": "label_values(cf_application_info{environment=~\"$environment\",deployment=~\"$bosh_deployment\",organization_name=~\"$cf_organization_name\", space_name=~\"$cf_space_name\"}, application_name)"
   },
   {
    "name": "cf_application_id",
    "label": "Application ID",
    "query": "label_values(cf_application_info{environment=~\"$environment\",deployment=~\"$bosh_deployment\",organization_name=~\"$cf_organization_name\", space_name=~\"$cf_space_name\",application_name=~\"$cf_application_name\"}, application_id)"
   }
  ]
 },
 "panels": [
  {
   "title": "Latency",
   "type": "graph",
   "description": "Application Latency.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(firehose_http_start_stop_client_request_duration_seconds_sum{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",application_id=~\"$cf_application_id\"} / firehose_http_start_stop_client_request_duration_seconds_count{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",application_id=~\"$cf_application_id\"})",
     "legendFormat": "Client"
    },
    {
     "expr": "avg(firehose_http_start_stop_server_request_duration_seconds_sum{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",application_id=~\"$cf_application_id\"} / firehose_http_start_stop_server_request_duration_seconds_count{environment=~\"$environment\",bosh_deployment=~\"$bosh_deployment\",application_id=~\"$cf_application_id\"})",
     "legendFormat": "Server"
    }
   ]
  },
  {
   "title": "Client Latency (quantiles)",
   "type": "graph",
   "description": "Client Latency by Quantiles.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(firehose_http_start_stop_client_request_duration_seconds{environment=~\"$environment\",bosh_deployment=~\"$environment\",application_id=~\"$cf_application_id\"}) by(quantile)",
     "legendFormat": "{{ quantile }}"
    }
   ]
  },
  {
   "title": "Server Latency (quantiles)",
   "type": "graph",
   "description": "Server Latency by Quantiles.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(firehose_http_start_stop_server_request_duration_seconds{environment=~\"$environment\",bosh_deployment=~\"$environment\",application_id=~\"$cf_application_id\"}) by(quantile)",
     "legendFormat": "{{ quantile }}"
    }
   ]
  }
 ]
}